/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "arqllyuqyjiiqpqumhsn"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFycWxseXVxeWppaXFwcXVtaHNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzNTAwNjksImV4cCI6MjA4NjkyNjA2OX0.Szg_ZtC5LjFcpczbwBsTOcVdqj8ijRk-q-Ffd5fcweo"